################################################################
# Traefik configuration
################################################################
<% if_p('traefik.base_config') do |conf| %><%= conf %><% end %>