################################################################
# Traefik configuration
################################################################
<% if_p('traefik.config') do |conf| %><%= conf %><% end %>