---
name: ((deployment_name))

instance_groups:
  - name: traefik
    instances: 1
    azs: [ z1 ]
    jobs:
      - name: traefik
        release: traefik
        properties:
          traefik:
            log_level: INFO
            access_logs: { enabled: true }
            http: { enabled: true }
            tls:
              cert: ((traefik_tls))
          bpm:
            enabled: true
      - name: bpm
        release: bpm
      - name: smoke-tests
        release: traefik
    stemcell: default
    vm_type: default
    persistent_disk_type: default
    env:
      bosh: { swap_size: 0 }
    networks:
      - name: ((network_name))

variables:
  - name: traefikCA
    type: certificate
    options:
      is_ca: true
      common_name: traefikCA

  - name: traefik_tls
    type: certificate
    options:
      ca: traefikCA
      common_name: ((traefik_domain))
      alternative_names:
        - ((traefik_domain))
        - "*.((traefik_domain))"

features:
  use_dns_addresses: true

update:
  serial: true # instance groups to be deployed sequentially.

  canaries: 1
  canary_watch_time: 1000-5000

  max_in_flight: 1
  update_watch_time: 1000-5000

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: traefik
  sha1: f646efe0cae1d09a61991f7e0824f15e9c64dd78
  stemcell:
    os: ubuntu-xenial
    version: "456.30"
  url: https://s3.eu-west-3.amazonaws.com/traefik-boshrelease/compiled-releases/traefik/traefik-1.8.0-ubuntu-xenial-456.30-20191018-213412-875064903-20191018213413.tgz
  version: 1.8.0
- name: bpm
  sha1: b41556af773ea9aec93dd21a9bbf129200849eed
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.3
  version: 1.1.3
