---
name: ((deployment_name))

instance_groups:
  - name: traefik
    instances: 1
    azs: [ z1 ]
    jobs:
      - name: traefik
        release: traefik
        properties:
          traefik:
            log_level: INFO
            access_logs: { enabled: true }
            http: { enabled: true }
            tls:
              cert: ((traefik_tls))
      - name: smoke-tests
        release: traefik
    stemcell: default
    vm_type: default
    persistent_disk_type: default
    env:
      bosh: { swap_size: 0 }
    networks:
      - name: ((network_name))

variables:
  - name: traefikCA
    type: certificate
    options:
      is_ca: true
      common_name: traefikCA

  - name: traefik_tls
    type: certificate
    options:
      ca: traefikCA
      common_name: ((traefik_domain))
      alternative_names:
        - ((traefik_domain))
        - "*.((traefik_domain))"

features:
  use_dns_addresses: true

update:
  serial: true # instance groups to be deployed sequentially.

  canaries: 1
  canary_watch_time: 1000-5000

  max_in_flight: 1
  update_watch_time: 1000-5000

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: traefik
  sha1: 723567cee6c39ea0eda16cb3edce083d45482787
  stemcell:
    os: ubuntu-xenial
    version: "250.48"
  url: https://s3.eu-west-3.amazonaws.com/traefik-boshrelease/compiled-releases/traefik/traefik-1.5.0-ubuntu-xenial-250.48-20190518-071142-524103793-20190518071143.tgz
  version: 1.5.0
