---
name: traefik

instance_groups:
  - name: traefik
    instances: 1
    azs: [ z1 ]
    jobs:
      - name: traefik
        release: traefik
        properties:
          traefik:
            log_level: INFO
            access_logs: { enabled: true }
            http: { enabled: true }
            tls:
              cert: ((traefik_tls))
    stemcell: default
    vm_type: default
    persistent_disk_type: default
    env:
      bosh: { swap_size: 0 }
    networks:
      - name: default

variables:
  - name: traefikCA
    type: certificate
    options:
      is_ca: true
      common_name: traefikCA

  - name: traefik_tls
    type: certificate
    options:
      ca: traefikCA
      common_name: ((traefik_domain))
      alternative_names:
        - ((traefik_domain))
        - "*.((traefik_domain))"

update:
  serial: true # instance groups to be deployed sequentially.

  canaries: 1
  canary_watch_time: 1000-5000

  max_in_flight: 1
  update_watch_time: 1000-5000

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: traefik
  sha1: 375f3d1c3615e38691bacfefeb7223c01dfef2e6
  stemcell:
    os: ubuntu-xenial
    version: "250.29"
  url: https://s3.eu-west-3.amazonaws.com/traefik-boshrelease/compiled-releases/traefik/traefik-1.3.0-ubuntu-xenial-250.29-20190414-014843-75886571-20190414014844.tgz
  version: 1.3.0
