---
name: ((deployment_name))

instance_groups:
  - name: traefik
    instances: 1
    azs: [ z1 ]
    jobs:
      - name: traefik
        release: traefik
        properties:
          traefik:
            log_level: INFO
            access_logs: { enabled: true }
            http: { enabled: true }
            tls:
              cert: ((traefik_tls))
          bpm:
            enabled: true
      - name: bpm
        release: bpm
      - name: smoke-tests
        release: traefik
    stemcell: default
    vm_type: default
    persistent_disk_type: default
    env:
      bosh: { swap_size: 0 }
    networks:
      - name: ((network_name))

variables:
  - name: traefikCA
    type: certificate
    options:
      is_ca: true
      common_name: traefikCA

  - name: traefik_tls
    type: certificate
    options:
      ca: traefikCA
      common_name: ((traefik_domain))
      alternative_names:
        - ((traefik_domain))
        - "*.((traefik_domain))"

features:
  use_dns_addresses: true

update:
  serial: true # instance groups to be deployed sequentially.

  canaries: 1
  canary_watch_time: 1000-5000

  max_in_flight: 1
  update_watch_time: 1000-5000

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: traefik
  sha1: 86fd75ba7270c4668a37d0475ae73f2b6a4242db
  stemcell:
    os: ubuntu-xenial
    version: "250.48"
  url: https://github.com/gstackio/traefik-boshrelease/releases/download/v1.7.0/traefik-1.7.0.tgz
  version: 1.7.0
- name: bpm
  sha1: 41df19697d6a69d2552bc2c132928157fa91abe0
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.4
  version: 1.0.4
