---
name: traefik-single

instance_groups:
  - name: traefik
    instances: 1
    azs: [ z1 ]
    jobs:
      - name: traefik
        release: traefik
        properties:
          bpm:
            enabled: true
          traefik:
            config: |
              entryPoints:
                web:
                  address: ":80"
                web-secure:
                  address: ":443"
              providers:
                # Enable the file provider to define routers / middlewares / services in a file
                file:
                  directory: /etc/traefik/conf.d
                  watch: true
              certificatesResolvers:
                default:
                  acme:
                    email: mnikolai@evoila.de
                    storage: /var/vcap/store/traefik/acme
                    httpChallenge:
                      # used during the challenge
                      entryPoint: web
              log:
                filePath: /var/vcap/sys/log/traefik/traefik.log
              accessLog:
                filePath: /var/vcap/sys/log/traefik/access.log
 
      - name: bpm
        release: bpm
    stemcell: default
    vm_type: default
    persistent_disk_type: default
    env:
      bosh: { swap_size: 0 }
    networks:
      - name: default

update:
  serial: false

  canaries: 1
  canary_watch_time: 1000-5000

  max_in_flight: 1
  update_watch_time: 1000-5000

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: bpm
  sha1: 5bad6161dbbcf068830a100b6a76056fe3b99bc8
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.6
  version: 1.1.6
- name: traefik 
  version: latest