---
meta:
  name:    traefik
  target:  gk
  url:     https://ci.gstack.io

  test-errands: "smoke-tests"

  initial_version: "1.3.0"

  manifest:
    directory: deployment
    vars: |
      ---
      deployment_name: traefik-testflight
      network_name: default
      traefik_domain: example.com
      api_username: admin-testflight
      smoke_tests_frontend_hostname: mockbin.example.com
    vars-pr: |
      ---
      deployment_name: traefik-testflight-pr
      network_name: default
      traefik_domain: example.com
      api_username: admin-testflight
      smoke_tests_frontend_hostname: mockbin.example.com
    operator_file_paths:
      deployment/operations/testflight/smoke-tests-setup.yml
      deployment/operations/enable-api.yml
      deployment/operations/enable-rest.yml

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  bosh-lite:
    target:   ((bosh-lite-environment))
    cacert:   ((bosh-lite-ca-cert))
    username: ((bosh-lite-client))
    password: ((bosh-lite-client-secret))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: eu-west-3
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  gstackio
    repo:   (( grab meta.pipeline ))
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  bosh:
    stemcell:
      cpi: "warden-boshlite"

  test-errands: smoke-tests

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       (( concat "#" meta.name "-boshrelease" ))
    blob_success:  '(( concat ": New version of  was detected, and updated in master. <" meta.url "/teams//pipelines/| Cut a new release?>" ))'
    blob_failure:  '(( concat ": :airplane_arriving: <" meta.url "/teams//pipelines//jobs//builds/| Failed to update the blob for >" ))'
